name: storage_infomation
description: Storage Infomation
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  local_auth: ^0.4.0+1 #^0.5.2+2
  flutter_secure_storage: ^3.3.5
  password_strength: ^0.1.2

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  dynamic_theme: ^1.0.0

  # provider: any
  sqflite: ^1.3.2+1

  # get_it: any
  encrypt: ^4.1.0
  path_provider: ^1.6.24
  shared_preferences: ^0.5.12+4
  flutter_material_color_picker: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  ios: true
  android: true
  image_path: "assets/key.png"

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/key.png
  #  - images/a_dot_ham.jpeg
  fonts:
    - family: GoogleSans
      fonts:
        - asset: assets/fonts/GoogleSansRegular.ttf
    - family: Title
      fonts:
        - asset: assets/fonts/Title.otf
    - family: Subtitle
      fonts:
        - asset: assets/fonts/Subtitle.otf